# shellcheck shell=bash

################################################################################
# Setup useful delete commands
################################################################################

# Delete .DS_Store files generated by macOS
alias delete.ds="find . -name '.DS_Store' -type f -print -delete"

# Delete @eaDir directories generated by Synology NAS devices
delete.ea() {
    find . -iname '@eaDir' -type d -exec rm -rf {} \;
}
