# shellcheck shell=bash

################################################################################
## This file generated by sqlclGenerateTNSAliases
################################################################################
## SQLcl Binary                    : ""
## Prefix                          : "sql.personal.dev."
## Name generation function        : "defaultAliasNameFormatFunction"
## Additional aliases function     : ""
################################################################################

alias sql.personal.dev.lyleatp1_high='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_lyleatp1.zip'\'' -i '\''lyleatp1_high'\'''
alias sql.personal.dev.lyleatp1_low='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_lyleatp1.zip'\'' -i '\''lyleatp1_low'\'''
alias sql.personal.dev.lyleatp1_medium='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_lyleatp1.zip'\'' -i '\''lyleatp1_medium'\'''
alias sql.personal.dev.lyleatp1_tp='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_lyleatp1.zip'\'' -i '\''lyleatp1_tp'\'''
alias sql.personal.dev.lyleatp1_tpurgent='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_lyleatp1.zip'\'' -i '\''lyleatp1_tpurgent'\'''
