# shellcheck shell=bash

################################################################################
## This file generated by sqlclGenerateTNSAliases
################################################################################
## SQLcl Binary                    : ""
## Prefix                          : "sql.oracle.hcgbu.unstable.gpas."
## Name generation function        : "defaultAliasNameFormatFunction"
## Additional aliases function     : ""
################################################################################

alias sql.oracle.hcgbu.unstable.gpas.gpasunstableatp_high='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_GPASUNSTABLEATP.zip'\'' -i '\''gpasunstableatp_high'\'''
alias sql.oracle.hcgbu.unstable.gpas.gpasunstableatp_low='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_GPASUNSTABLEATP.zip'\'' -i '\''gpasunstableatp_low'\'''
alias sql.oracle.hcgbu.unstable.gpas.gpasunstableatp_medium='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_GPASUNSTABLEATP.zip'\'' -i '\''gpasunstableatp_medium'\'''
alias sql.oracle.hcgbu.unstable.gpas.gpasunstableatp_tp='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_GPASUNSTABLEATP.zip'\'' -i '\''gpasunstableatp_tp'\'''
alias sql.oracle.hcgbu.unstable.gpas.gpasunstableatp_tpurgent='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_GPASUNSTABLEATP.zip'\'' -i '\''gpasunstableatp_tpurgent'\'''
