# shellcheck shell=bash

################################################################################
## This file generated by sqlclGenerateTNSAliases
################################################################################
## SQLcl Binary                    : ""
## Prefix                          : "sql.oracle.hcgbu.dev.gpas."
## Name generation function        : "defaultAliasNameFormatFunction"
## Additional aliases function     : ""
################################################################################

alias sql.oracle.hcgbu.dev.gpas.gpasdevatp_high='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_GPASDEVATP.zip'\'' -i '\''gpasdevatp_high'\'''
alias sql.oracle.hcgbu.dev.gpas.gpasdevatp_low='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_GPASDEVATP.zip'\'' -i '\''gpasdevatp_low'\'''
alias sql.oracle.hcgbu.dev.gpas.gpasdevatp_medium='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_GPASDEVATP.zip'\'' -i '\''gpasdevatp_medium'\'''
alias sql.oracle.hcgbu.dev.gpas.gpasdevatp_tp='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_GPASDEVATP.zip'\'' -i '\''gpasdevatp_tp'\'''
alias sql.oracle.hcgbu.dev.gpas.gpasdevatp_tpurgent='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_GPASDEVATP.zip'\'' -i '\''gpasdevatp_tpurgent'\'''
