# shellcheck shell=bash

################################################################################
## This file generated by sqlclGenerateTNSAliases
################################################################################
## SQLcl Binary                    : ""
## Prefix                          : "sql.vna.dev."
## Name generation function        : "defaultAliasNameFormatFunction"
## Additional aliases function     : ""
################################################################################

alias sql.vna.dev.dbvna_high='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_DBVNA.zip'\'' -i '\''dbvna_high'\'''
alias sql.vna.dev.dbvna_low='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_DBVNA.zip'\'' -i '\''dbvna_low'\'''
alias sql.vna.dev.dbvna_medium='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_DBVNA.zip'\'' -i '\''dbvna_medium'\'''
alias sql.vna.dev.dbvna_tp='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_DBVNA.zip'\'' -i '\''dbvna_tp'\'''
alias sql.vna.dev.dbvna_tpurgent='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_DBVNA.zip'\'' -i '\''dbvna_tpurgent'\'''
