# shellcheck shell=bash

################################################################################
## This file generated by sqlclGenerateTNSAliases
################################################################################
## SQLcl Binary                    : ""
## Prefix                          : "sql.oracle.hcgbu.dev.ohpo."
## Name generation function        : "defaultAliasNameFormatFunction"
## Additional aliases function     : ""
################################################################################

alias sql.oracle.hcgbu.dev.ohpo.ohpedephx1_high='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_OHPEDEPHX1.zip'\'' -i '\''ohpedephx1_high'\'''
alias sql.oracle.hcgbu.dev.ohpo.ohpedephx1_low='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_OHPEDEPHX1.zip'\'' -i '\''ohpedephx1_low'\'''
alias sql.oracle.hcgbu.dev.ohpo.ohpedephx1_medium='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_OHPEDEPHX1.zip'\'' -i '\''ohpedephx1_medium'\'''
alias sql.oracle.hcgbu.dev.ohpo.ohpedephx1_tp='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_OHPEDEPHX1.zip'\'' -i '\''ohpedephx1_tp'\'''
alias sql.oracle.hcgbu.dev.ohpo.ohpedephx1_tpurgent='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_OHPEDEPHX1.zip'\'' -i '\''ohpedephx1_tpurgent'\'''
