# shellcheck shell=bash

################################################################################
## This file generated by sqlclGenerateTNSAliases
################################################################################
## SQLcl Binary                    : ""
## Prefix                          : "sql."
## Name generation function        : "defaultAliasNameFormatFunction"
## Additional aliases function     : ""
################################################################################

alias sql.oracle.xgbu_ace.dev.cdb.acddev19_iad19d='sqlclConnectHelper -i '\''oracle.xgbu_ace.dev.cdb.acddev19_iad19d'\'''
alias sql.oracle.xgbu_ace.dev.cdb.tmplt_apx_23_2_0='sqlclConnectHelper -i '\''oracle.xgbu_ace.dev.cdb.tmplt_apx_23_2_0'\'''
alias sql.oracle.fbgbu.dev.invapxpdb='sqlclConnectHelper -i '\''oracle.fbgbu.dev.invapxpdb'\'''
