# shellcheck shell=bash

################################################################################
## This file generated by sqlclGenerateTNSAliases
################################################################################
## SQLcl Binary                    : ""
## Prefix                          : "sql.oracle.hcgbu.dev.odr."
## Name generation function        : "defaultAliasNameFormatFunction"
## Additional aliases function     : ""
################################################################################

alias sql.oracle.hcgbu.dev.odr.hcgbuodrdev_high='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_hcgbuodrdev.zip'\'' -i '\''hcgbuodrdev_high'\'''
alias sql.oracle.hcgbu.dev.odr.hcgbuodrdev_low='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_hcgbuodrdev.zip'\'' -i '\''hcgbuodrdev_low'\'''
alias sql.oracle.hcgbu.dev.odr.hcgbuodrdev_medium='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_hcgbuodrdev.zip'\'' -i '\''hcgbuodrdev_medium'\'''
alias sql.oracle.hcgbu.dev.odr.hcgbuodrdev_tp='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_hcgbuodrdev.zip'\'' -i '\''hcgbuodrdev_tp'\'''
alias sql.oracle.hcgbu.dev.odr.hcgbuodrdev_tpurgent='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_hcgbuodrdev.zip'\'' -i '\''hcgbuodrdev_tpurgent'\'''
