# shellcheck shell=bash

################################################################################
## This file generated by sqlclGenerateTNSAliases
################################################################################
## SQLcl Binary                    : ""
## Prefix                          : "sql.personal.dev."
## Name generation function        : "defaultAliasNameFormatFunction"
## Additional aliases function     : ""
################################################################################

alias sql.personal.dev.oralyleatp1_high='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_oralyleatp1.zip'\'' -i '\''oralyleatp1_high'\'''
alias sql.personal.dev.oralyleatp1_low='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_oralyleatp1.zip'\'' -i '\''oralyleatp1_low'\'''
alias sql.personal.dev.oralyleatp1_medium='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_oralyleatp1.zip'\'' -i '\''oralyleatp1_medium'\'''
alias sql.personal.dev.oralyleatp1_tp='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_oralyleatp1.zip'\'' -i '\''oralyleatp1_tp'\'''
alias sql.personal.dev.oralyleatp1_tpurgent='sqlclConnectHelper -c '\''/Users/jlyle/.config/oracle/wallets/Wallet_oralyleatp1.zip'\'' -i '\''oralyleatp1_tpurgent'\'''
