# shellcheck shell=bash

################################################################################
## This file generated by sqlclGenerateOIDAliases
################################################################################
## SQLcl Binary                    : ""
## Prefix                          : "sql.oracle.xgbu_ace.dev."
## Name generation function        : "formatXgbuLdapAliasNames"
## Additional aliases function     : "additionalXgbuLdapAliases"
## LDAP Host                       : "xgbu-ace-api-test.appoci.oraclecorp.com"
## LDAP Port                       : "389"
## LDAP Base                       : "dc=xgbu-ace,dc=com"
## LDAP excluded contexts          :
##    - oraclecontext
################################################################################

############################################################
## acme_oci
############################################################
alias sql.oracle.xgbu_ace.dev.acme_oci.gad_2075='LDAPCON='\''jdbc:oracle:thin:@ldap://xgbu-ace-api-test.appoci.oraclecorp.com:389/#ENTRY#,cn=acme_oci,dc=xgbu-ace,dc=com'\'' sqlclConnectHelper -i '\''xgbu_ace_acme_oci_gad_2075'\'''
alias apex.oracle.xgbu_ace.dev.acme_oci.gad_2075.ords='open '\''https://xgbu-ace-ords.appoci.oraclecorp.com/ords/xgbu_ace_acme_oci_gad_2075/'\'''
alias apex.oracle.xgbu_ace.dev.acme_oci.gad_2075.wtss='open '\''https://xgbu-ace-wtss.appoci.oraclecorp.com/ords/xgbu_ace_acme_oci_gad_2075/'\'''
alias sql.oracle.xgbu_ace.dev.acme_oci.main='LDAPCON='\''jdbc:oracle:thin:@ldap://xgbu-ace-api-test.appoci.oraclecorp.com:389/#ENTRY#,cn=acme_oci,dc=xgbu-ace,dc=com'\'' sqlclConnectHelper -i '\''xgbu_ace_acme_oci_main'\'''
alias apex.oracle.xgbu_ace.dev.acme_oci.main.ords='open '\''https://xgbu-ace-ords.appoci.oraclecorp.com/ords/xgbu_ace_acme_oci_main/'\'''
alias apex.oracle.xgbu_ace.dev.acme_oci.main.wtss='open '\''https://xgbu-ace-wtss.appoci.oraclecorp.com/ords/xgbu_ace_acme_oci_main/'\'''
alias sql.oracle.xgbu_ace.dev.acme_oci.temp_pipeline_test='LDAPCON='\''jdbc:oracle:thin:@ldap://xgbu-ace-api-test.appoci.oraclecorp.com:389/#ENTRY#,cn=acme_oci,dc=xgbu-ace,dc=com'\'' sqlclConnectHelper -i '\''xgbu_ace_acme_oci_temp_pipeline_test'\'''
alias apex.oracle.xgbu_ace.dev.acme_oci.temp_pipeline_test.ords='open '\''https://xgbu-ace-ords.appoci.oraclecorp.com/ords/xgbu_ace_acme_oci_temp_pipeline_test/'\'''
alias apex.oracle.xgbu_ace.dev.acme_oci.temp_pipeline_test.wtss='open '\''https://xgbu-ace-wtss.appoci.oraclecorp.com/ords/xgbu_ace_acme_oci_temp_pipeline_test/'\'''
alias sql.oracle.xgbu_ace.dev.acme_oci.test_33191='LDAPCON='\''jdbc:oracle:thin:@ldap://xgbu-ace-api-test.appoci.oraclecorp.com:389/#ENTRY#,cn=acme_oci,dc=xgbu-ace,dc=com'\'' sqlclConnectHelper -i '\''xgbu_ace_acme_oci_test_33191'\'''
alias apex.oracle.xgbu_ace.dev.acme_oci.test_33191.ords='open '\''https://xgbu-ace-ords.appoci.oraclecorp.com/ords/xgbu_ace_acme_oci_test_33191/'\'''
alias apex.oracle.xgbu_ace.dev.acme_oci.test_33191.wtss='open '\''https://xgbu-ace-wtss.appoci.oraclecorp.com/ords/xgbu_ace_acme_oci_test_33191/'\'''
alias sql.oracle.xgbu_ace.dev.acme_oci.test_35231='LDAPCON='\''jdbc:oracle:thin:@ldap://xgbu-ace-api-test.appoci.oraclecorp.com:389/#ENTRY#,cn=acme_oci,dc=xgbu-ace,dc=com'\'' sqlclConnectHelper -i '\''xgbu_ace_acme_oci_test_35231'\'''
alias apex.oracle.xgbu_ace.dev.acme_oci.test_35231.ords='open '\''https://xgbu-ace-ords.appoci.oraclecorp.com/ords/xgbu_ace_acme_oci_test_35231/'\'''
alias apex.oracle.xgbu_ace.dev.acme_oci.test_35231.wtss='open '\''https://xgbu-ace-wtss.appoci.oraclecorp.com/ords/xgbu_ace_acme_oci_test_35231/'\'''

############################################################
## anishah
############################################################

############################################################
## baseline_database_pool_19c
############################################################
alias sql.oracle.xgbu_ace.dev.baseline_database_pool_19c.main='LDAPCON='\''jdbc:oracle:thin:@ldap://xgbu-ace-api-test.appoci.oraclecorp.com:389/#ENTRY#,cn=baseline_database_pool_19c,dc=xgbu-ace,dc=com'\'' sqlclConnectHelper -i '\''xgbu_ace_baseline_database_pool_19c_main'\'''
alias apex.oracle.xgbu_ace.dev.baseline_database_pool_19c.main.ords='open '\''https://xgbu-ace-ords.appoci.oraclecorp.com/ords/xgbu_ace_baseline_database_pool_19c_main/'\'''
alias apex.oracle.xgbu_ace.dev.baseline_database_pool_19c.main.wtss='open '\''https://xgbu-ace-wtss.appoci.oraclecorp.com/ords/xgbu_ace_baseline_database_pool_19c_main/'\'''

############################################################
## baseline_database_pool_26ai
############################################################
alias sql.oracle.xgbu_ace.dev.baseline_database_pool_26ai.main='LDAPCON='\''jdbc:oracle:thin:@ldap://xgbu-ace-api-test.appoci.oraclecorp.com:389/#ENTRY#,cn=baseline_database_pool_26ai,dc=xgbu-ace,dc=com'\'' sqlclConnectHelper -i '\''xgbu_ace_baseline_database_pool_26ai_main'\'''
alias apex.oracle.xgbu_ace.dev.baseline_database_pool_26ai.main.ords='open '\''https://xgbu-ace-ords.appoci.oraclecorp.com/ords/xgbu_ace_baseline_database_pool_26ai_main/'\'''
alias apex.oracle.xgbu_ace.dev.baseline_database_pool_26ai.main.wtss='open '\''https://xgbu-ace-wtss.appoci.oraclecorp.com/ords/xgbu_ace_baseline_database_pool_26ai_main/'\'''

############################################################
## baseline_database_pool
############################################################
alias sql.oracle.xgbu_ace.dev.baseline_database_pool.acme_oci_pipeline_146_build_2='LDAPCON='\''jdbc:oracle:thin:@ldap://xgbu-ace-api-test.appoci.oraclecorp.com:389/#ENTRY#,cn=baseline_database_pool,dc=xgbu-ace,dc=com'\'' sqlclConnectHelper -i '\''xgbu_ace_acme_oci_pipeline_146_build_2'\'''
alias apex.oracle.xgbu_ace.dev.baseline_database_pool.acme_oci_pipeline_146_build_2.ords='open '\''https://xgbu-ace-ords.appoci.oraclecorp.com/ords/xgbu_ace_acme_oci_pipeline_146_build_2/'\'''
alias apex.oracle.xgbu_ace.dev.baseline_database_pool.acme_oci_pipeline_146_build_2.wtss='open '\''https://xgbu-ace-wtss.appoci.oraclecorp.com/ords/xgbu_ace_acme_oci_pipeline_146_build_2/'\'''
alias sql.oracle.xgbu_ace.dev.baseline_database_pool.acme_oci_pipeline_8_build_56='LDAPCON='\''jdbc:oracle:thin:@ldap://xgbu-ace-api-test.appoci.oraclecorp.com:389/#ENTRY#,cn=baseline_database_pool,dc=xgbu-ace,dc=com'\'' sqlclConnectHelper -i '\''xgbu_ace_acme_oci_pipeline_8_build_56'\'''
alias apex.oracle.xgbu_ace.dev.baseline_database_pool.acme_oci_pipeline_8_build_56.ords='open '\''https://xgbu-ace-ords.appoci.oraclecorp.com/ords/xgbu_ace_acme_oci_pipeline_8_build_56/'\'''
alias apex.oracle.xgbu_ace.dev.baseline_database_pool.acme_oci_pipeline_8_build_56.wtss='open '\''https://xgbu-ace-wtss.appoci.oraclecorp.com/ords/xgbu_ace_acme_oci_pipeline_8_build_56/'\'''
alias sql.oracle.xgbu_ace.dev.baseline_database_pool.main='LDAPCON='\''jdbc:oracle:thin:@ldap://xgbu-ace-api-test.appoci.oraclecorp.com:389/#ENTRY#,cn=baseline_database_pool,dc=xgbu-ace,dc=com'\'' sqlclConnectHelper -i '\''xgbu_ace_baseline_database_pool_main'\'''
alias apex.oracle.xgbu_ace.dev.baseline_database_pool.main.ords='open '\''https://xgbu-ace-ords.appoci.oraclecorp.com/ords/xgbu_ace_baseline_database_pool_main/'\'''
alias apex.oracle.xgbu_ace.dev.baseline_database_pool.main.wtss='open '\''https://xgbu-ace-wtss.appoci.oraclecorp.com/ords/xgbu_ace_baseline_database_pool_main/'\'''

############################################################
## crueppri
############################################################
alias sql.oracle.xgbu_ace.dev.crueppri.main='LDAPCON='\''jdbc:oracle:thin:@ldap://xgbu-ace-api-test.appoci.oraclecorp.com:389/#ENTRY#,cn=crueppri,dc=xgbu-ace,dc=com'\'' sqlclConnectHelper -i '\''xgbu_ace_crueppri_main'\'''
alias apex.oracle.xgbu_ace.dev.crueppri.main.ords='open '\''https://xgbu-ace-ords.appoci.oraclecorp.com/ords/xgbu_ace_crueppri_main/'\'''
alias apex.oracle.xgbu_ace.dev.crueppri.main.wtss='open '\''https://xgbu-ace-wtss.appoci.oraclecorp.com/ords/xgbu_ace_crueppri_main/'\'''

############################################################
## db_tracker
############################################################
alias sql.oracle.xgbu_ace.dev.db_tracker.tag_test_joeg='LDAPCON='\''jdbc:oracle:thin:@ldap://xgbu-ace-api-test.appoci.oraclecorp.com:389/#ENTRY#,cn=db_tracker,dc=xgbu-ace,dc=com'\'' sqlclConnectHelper -i '\''xgbu_ace_tag_test_joeg'\'''
alias apex.oracle.xgbu_ace.dev.db_tracker.tag_test_joeg.ords='open '\''https://xgbu-ace-ords.appoci.oraclecorp.com/ords/xgbu_ace_tag_test_joeg/'\'''
alias apex.oracle.xgbu_ace.dev.db_tracker.tag_test_joeg.wtss='open '\''https://xgbu-ace-wtss.appoci.oraclecorp.com/ords/xgbu_ace_tag_test_joeg/'\'''

############################################################
## metadata
############################################################
alias sql.oracle.xgbu_ace.dev.metadata.stage='LDAPCON='\''jdbc:oracle:thin:@ldap://xgbu-ace-api-test.appoci.oraclecorp.com:389/#ENTRY#,cn=metadata,dc=xgbu-ace,dc=com'\'' sqlclConnectHelper -i '\''xgbu_ace_metadata_stage'\'''
alias apex.oracle.xgbu_ace.dev.metadata.stage.ords='open '\''https://xgbu-ace-ords.appoci.oraclecorp.com/ords/xgbu_ace_metadata_stage/'\'''
alias apex.oracle.xgbu_ace.dev.metadata.stage.wtss='open '\''https://xgbu-ace-wtss.appoci.oraclecorp.com/ords/xgbu_ace_metadata_stage/'\'''
