#!/usr/bin/env zsh
# shellcheck shell=bash

################################################################################
################################################################################
##  .zshenv
##
##  ZSH configuration file order:
##      .zshenv
##      .zprofile
##      .zshrc
##      .zlogin
##      .zlogout
##
##  This file is used only to set environment variables
##
################################################################################
################################################################################

##
##  XDG
##
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_BIN_HOME="${HOME}/.local/bin"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"
if [[ "${OSTYPE}" == "darwin"* ]]; then
    export XDG_RUNTIME_DIR="$(getconf 'DARWIN_USER_TEMP_DIR')"
else
    export XDG_RUNTIME_DIR="/run/user/${UID}"
fi

##
##  ZSH
##
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"

##
##  Internationalization
##
export LANG=en_US.UTF-8

##
##  Personal Setup
##
export PERSONAL_ZSH_SETUP_SCRIPTS_DIR="${ZDOTDIR}/scripts"
export PERSONAL_BIN_DIR="${XDG_CONFIG_HOME}/bin"
export PERSONAL_AUTOLOAD_DIR="${XDG_CONFIG_HOME}/auto_load"
export PERSONAL_AUTOSOURCE_DIR="${XDG_CONFIG_HOME}/auto_source"

##
##  Starship
##
export STARSHIP_CONFIG="${XDG_CONFIG_HOME}/starship/starship.toml"
export STARSHIP_CACHE="${XDG_CONFIG_HOME}/starship/cache"
