[settings]
idiomatic_version_file_enable_tools = ["node"]

[settings.python]
compile = false

[tools]
"aqua:oracle.com/sqlcl" = "26.1.2.132.1334"
java = "oracle-graalvm-17"
liquibase = "latest"
node = "lts"
python = "3"
usage = "latest"
