#!/usr/bin/env zsh
# shellcheck shell=bash

################################################################################
################################################################################
##  .zshrc
##
##  ZSH configuration file order:
##      .zshenv
##      .zprofile
##      .zshrc
##      .zlogin
##      .zlogout
##
##  This file is the main ZSH configuration file
##
################################################################################
################################################################################

# Set shell options
source "${PERSONAL_ZSH_SETUP_SCRIPTS_DIR}/options.zsh"

# Set ZSH ZStyle settings
source "${PERSONAL_ZSH_SETUP_SCRIPTS_DIR}/zstyle.zsh"

# Install, configure, and use ZSH Antidote
source "${PERSONAL_ZSH_SETUP_SCRIPTS_DIR}/antidote.zsh"

# Set key bindings
source "${PERSONAL_ZSH_SETUP_SCRIPTS_DIR}/bindkey.zsh"

# Set path and fpath to be unique arrays
typeset -U path fpath

# Add personal bin and local bin to PATH
path=(
    "${PERSONAL_BIN_DIR}"
    "${HOME}/.local/bin"
    "${path[@]}"
)

# Add personal autoload and site-functions to FPATH
fpath=(
    "${PERSONAL_AUTOLOAD_DIR}"
    "${XDG_DATA_HOME}/zsh/site-functions"
    "${fpath[@]}"
)

# Autoload all the files in PERSONAL_AUTOLOAD_DIR
for autoload_file in "${PERSONAL_AUTOLOAD_DIR}/"*(.N); do
    autoload -Uz "${autoload_file:t}"
done
unset autoload_file

# Source all the files in PERSONAL_AUTOSOURCE_DIR in sorted order
for autosource_file ("${PERSONAL_AUTOSOURCE_DIR}"/*.zsh(N)); do
    source "${autosource_file}"
done
unset autosource_file
